name: Deploy with Omnipin

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Omnipin
        run: bun i -g omnipin@1.7.0

      - name: Build website
        run: cd next && bun i && bun run build

      - name: Deploy the site
        run: omnipin deploy next/out --strict --ens gtest.eth --safe 0xeE9eeaAB0Bb7D9B969D701f6f8212609EDeA252E
        env:
          OMNIPIN_FILECOIN_TOKEN: ${{ secrets.OMNIPIN_FILECOIN_TOKEN }}
          OMNIPIN_PK: ${{ secrets.OMNIPIN_PK }}
